import { Config } from "@stencil/core";

export const config: Config = {
  namespace: "gclass-tests-stencil",

  // srcDir is where Stencil looks for index.html. The www output target reads
  // that file as its template, injects the compiled script and the global
  // stylesheet into it, and writes the result to www/. Putting index.html at
  // the project root instead silently produces a www/ with no HTML in it.
  srcDir: "src",

  // src/styles.css is generated by `npm run build:css` (the Tailwind CLI step,
  // which runs first) because Stencil drives its own bundler and does not run a
  // PostCSS or Tailwind pipeline over component styles. globalStyle is injected
  // into index.html at build time.
  //
  // There is deliberately no globalScript. gclass-anims is imported by the
  // component that starts it (gc-page.tsx), which is where the DOM is complete,
  // so there is nothing for a page-level script to do.
  globalStyle: "src/styles.css",

  outputTargets: [
    // The `www` target is the static, client-only build that
    // scripts/build-pages.mjs stages. Stencil also emits a lazy-loadable
    // library build by default; that is not what gets deployed.
    {
      type: "www",
      dir: "www",
      serviceWorker: null,
      empty: true,
    },
  ],
};
