// Elm compiles to a single ES module (src/elm.js, generated by
// `npm run build:elm` before this file is ever bundled). That module exposes a
// global `Elm` namespace, so it is imported as a side-effectful module and the
// namespace is read off it.
//
// The whole integration is these two calls in this order. Elm.init renders
// synchronously into #root, so the page is complete before initAnimations()
// walks it. Anything Elm inserts afterwards - the rows, when the model grows -
// is a real DOM insertion and the engine's MutationObserver picks it up without
// a second call.
import { Elm } from "./elm.js";
import { initAnimations } from "gclass-anims";
import "./styles.css";

Elm.Main.init({ node: document.getElementById("root") });

initAnimations();

initCopyButtons();

console.log("gclass-anims 1.0.0-beta.24 initialised (elm 0.19.3)");

// One delegated handler on document covers every code block's copy button,
// including any Elm renders later. The text is the block's content.
function initCopyButtons() {
  document.addEventListener("click", (event) => {
    const btn = event.target.closest("[data-copy]");
    if (!btn) return;

    const code = btn.parentElement.querySelector("code");
    if (!code) return;

    const done = (label) => {
      btn.textContent = label;
      btn.classList.add("text-ok");
      setTimeout(() => {
        btn.textContent = "Copy";
        btn.classList.remove("text-ok");
      }, 1400);
    };

    navigator.clipboard
      .writeText(code.innerText)
      .then(() => done("Copied"), () => done("Failed"));
  });
}