/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * The scroll-progress rule.
     * `.scroll-progress` is a modifier, not a behaviour: it sets no geometry of its
     * own, so the element needs real CSS or it collapses to nothing. The rule lives
     * in src/styles/tailwind.css under `.gc-bar`, which is why this component is
     * needed at all — the class alone would not render a visible bar.
     * Light DOM for the same reason as gc-row-list: the engine queries the document,
     * not a shadow tree.
     */
    interface GcBar {
    }
    /**
     * The page itself.
     * Stencil components return JSX, so the whole document below is a component
     * rather than static markup — that is the framework's own model, not a
     * workaround. index.html holds only the two custom elements and the script
     * Stencil injects.
     * Light DOM throughout, for the reason documented on gc-row-list.
     */
    interface GcPage {
    }
    /**
     * The live demo: rows added by a Stencil component.
     * Stencil re-renders by diffing its virtual DOM and inserting real elements for
     * anything new. That is the case gclass-anims' MutationObserver covers, so this
     * component never tells the animation engine anything.
     * Light DOM, deliberately. gclass-anims reads ordinary `class` attributes off
     * elements in the document, and shadow DOM would hide both the utility classes
     * and the watched elements from inside the tree. Every Stencil page that wants
     * GSAP animations has to make the same choice, so it is stated here rather than
     * left as a trap.
     */
    interface GcRowList {
    }
}
declare global {
    /**
     * The scroll-progress rule.
     * `.scroll-progress` is a modifier, not a behaviour: it sets no geometry of its
     * own, so the element needs real CSS or it collapses to nothing. The rule lives
     * in src/styles/tailwind.css under `.gc-bar`, which is why this component is
     * needed at all — the class alone would not render a visible bar.
     * Light DOM for the same reason as gc-row-list: the engine queries the document,
     * not a shadow tree.
     */
    interface HTMLGcBarElement extends Components.GcBar, HTMLStencilElement {
    }
    var HTMLGcBarElement: {
        prototype: HTMLGcBarElement;
        new (): HTMLGcBarElement;
    };
    /**
     * The page itself.
     * Stencil components return JSX, so the whole document below is a component
     * rather than static markup — that is the framework's own model, not a
     * workaround. index.html holds only the two custom elements and the script
     * Stencil injects.
     * Light DOM throughout, for the reason documented on gc-row-list.
     */
    interface HTMLGcPageElement extends Components.GcPage, HTMLStencilElement {
    }
    var HTMLGcPageElement: {
        prototype: HTMLGcPageElement;
        new (): HTMLGcPageElement;
    };
    /**
     * The live demo: rows added by a Stencil component.
     * Stencil re-renders by diffing its virtual DOM and inserting real elements for
     * anything new. That is the case gclass-anims' MutationObserver covers, so this
     * component never tells the animation engine anything.
     * Light DOM, deliberately. gclass-anims reads ordinary `class` attributes off
     * elements in the document, and shadow DOM would hide both the utility classes
     * and the watched elements from inside the tree. Every Stencil page that wants
     * GSAP animations has to make the same choice, so it is stated here rather than
     * left as a trap.
     */
    interface HTMLGcRowListElement extends Components.GcRowList, HTMLStencilElement {
    }
    var HTMLGcRowListElement: {
        prototype: HTMLGcRowListElement;
        new (): HTMLGcRowListElement;
    };
    interface HTMLElementTagNameMap {
        "gc-bar": HTMLGcBarElement;
        "gc-page": HTMLGcPageElement;
        "gc-row-list": HTMLGcRowListElement;
    }
}
declare namespace LocalJSX {
    /**
     * The scroll-progress rule.
     * `.scroll-progress` is a modifier, not a behaviour: it sets no geometry of its
     * own, so the element needs real CSS or it collapses to nothing. The rule lives
     * in src/styles/tailwind.css under `.gc-bar`, which is why this component is
     * needed at all — the class alone would not render a visible bar.
     * Light DOM for the same reason as gc-row-list: the engine queries the document,
     * not a shadow tree.
     */
    interface GcBar {
    }
    /**
     * The page itself.
     * Stencil components return JSX, so the whole document below is a component
     * rather than static markup — that is the framework's own model, not a
     * workaround. index.html holds only the two custom elements and the script
     * Stencil injects.
     * Light DOM throughout, for the reason documented on gc-row-list.
     */
    interface GcPage {
    }
    /**
     * The live demo: rows added by a Stencil component.
     * Stencil re-renders by diffing its virtual DOM and inserting real elements for
     * anything new. That is the case gclass-anims' MutationObserver covers, so this
     * component never tells the animation engine anything.
     * Light DOM, deliberately. gclass-anims reads ordinary `class` attributes off
     * elements in the document, and shadow DOM would hide both the utility classes
     * and the watched elements from inside the tree. Every Stencil page that wants
     * GSAP animations has to make the same choice, so it is stated here rather than
     * left as a trap.
     */
    interface GcRowList {
    }
    interface IntrinsicElements {
        "gc-bar": GcBar;
        "gc-page": GcPage;
        "gc-row-list": GcRowList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The scroll-progress rule.
             * `.scroll-progress` is a modifier, not a behaviour: it sets no geometry of its
             * own, so the element needs real CSS or it collapses to nothing. The rule lives
             * in src/styles/tailwind.css under `.gc-bar`, which is why this component is
             * needed at all — the class alone would not render a visible bar.
             * Light DOM for the same reason as gc-row-list: the engine queries the document,
             * not a shadow tree.
             */
            "gc-bar": LocalJSX.IntrinsicElements["gc-bar"] & JSXBase.HTMLAttributes<HTMLGcBarElement>;
            /**
             * The page itself.
             * Stencil components return JSX, so the whole document below is a component
             * rather than static markup — that is the framework's own model, not a
             * workaround. index.html holds only the two custom elements and the script
             * Stencil injects.
             * Light DOM throughout, for the reason documented on gc-row-list.
             */
            "gc-page": LocalJSX.IntrinsicElements["gc-page"] & JSXBase.HTMLAttributes<HTMLGcPageElement>;
            /**
             * The live demo: rows added by a Stencil component.
             * Stencil re-renders by diffing its virtual DOM and inserting real elements for
             * anything new. That is the case gclass-anims' MutationObserver covers, so this
             * component never tells the animation engine anything.
             * Light DOM, deliberately. gclass-anims reads ordinary `class` attributes off
             * elements in the document, and shadow DOM would hide both the utility classes
             * and the watched elements from inside the tree. Every Stencil page that wants
             * GSAP animations has to make the same choice, so it is stated here rather than
             * left as a trap.
             */
            "gc-row-list": LocalJSX.IntrinsicElements["gc-row-list"] & JSXBase.HTMLAttributes<HTMLGcRowListElement>;
        }
    }
}
